use "C:\Users\Erik\Desktop\NCES Data\ELS 02-12 with PETS\Unpacked\els02_by_f3_pets.dta", clear

keep STU_ID BYTXMSTD BYTXRSTD F3TXEESATC F3TXEESATM TXACTC TXACTM TXACTR TXACTE TXACTS TXEESATC TXEESATM TXEEACTC TXEEACTM TXSATM TXSATV TXSATC TXAPBIO TXAPCHE TXAPCGP TXAPCSA TXAPCSB TXAPLIT TXAPLAN TXAPEUH TXAPFLA TXAPFLI TXAPGER TXAPHAR TXAPLVE TXAPCAA TXAPCAB TXAPMAC TXAPMIC TXAPMT TXAPPB TXAPPCE TXAPPCM TXAPPSY TXAPSLA TXAPSLI TXAPSAD TXAPUSG TXAPUSH TXAPENV TXAPHUM TXAPLAT TXAPSTA TXAPSA2 TXAPSA3 TXAPWOR TXSATM1 TXSATM2 TXSATPH TXSATCH TXSATBY TXSATLI TXSATUS TXSATFR TXSATGE TXSATLA TXSATSP TXSATMH TXSATCL TXSATEP TXSATFL TXSATGL TXSATSL TXSATWH TXSATWR
 
mvdecode _all, mv(-1=.a \ -2=.b \ -3=.c \ -4=.d \ -5=.e \ -6=.f \ -7=.g \ -8=.h \ -9=.i)

